### PR TITLE
First version of register authentication portal

### PR DESCRIPTION
**Pull request by dladeira**

### CODE REVIEW

**Comment by h0lybyte** [comment]
Just to make it easier to get back to this branch, going to link it with the issue ticket.

https://github.com/KBVE/kbve/issues/2212

**Comment by dladeira** [comment]
> Can you update it so that it uses tailwindcss instead of inline style?

Added a couple colors to the tailwind configuration. Also I'd suggest to keep the height for the image in the stylesheet as for some reason tailwind doesn't have 30rem height, only 24, and that looks rather off.

**Comment by h0lybyte** [comment]
> > Can you update it so that it uses tailwindcss instead of inline style?
> 
> Added a couple colors to the tailwind configuration. Also I'd suggest to keep the height for the image in the stylesheet as for some reason tailwind doesn't have 30rem height, only 24, and that looks rather off.

https://tailwindcss.com/docs/height#arbitrary-values

To do 30rem height in tailwindcss, you would do `h-[30rem]`

**Comment by dladeira** [comment]
The more you know

**Comment by h0lybyte** [comment]
> The more you know

Before you work on login page , do you want me to merge in register ?

**Review by h0lybyte — APPROVED** [review]

**Comment by h0lybyte** [comment]
Going to merge this up and I will review it!

**Pull request merged**
